services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  fullstack:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fullstack_app
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    command: npm run dev
    depends_on:
      - mongo
    develop:
      watch:
        # sync complet du projet
        - action: sync
          path: ./
          target: /src
          ignore:
            - node_modules/
        # rebuild + restart si Dockerfile ou package.json change
        - action: sync+restart
          path: ./package.json
          target: /app/package.json
        - action: sync+restart
          path: ./Dockerfile
          target: /app/Dockerfile
        - action: sync+restart
          path: ./next.config.ts
          target: /app/next.config.ts

volumes:
  mongo_data: